spring:
  application:
    name:made-prj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
server:
  port: 8082
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package:
