server:
  port: 9003
spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          content-type: application/json
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched
          content-type: application/json
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: user
    password: 1234
    connection-timeout: 5s

