apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-rabbitmq
  labels:
    app: polar-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polar-rabbitmq
  template:
    metadata:
      labels:
        app: polar-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "1234"
          ports:
            - containerPort: 5672  # AMQP 포트
            - containerPort: 15672 # Management UI 포트
---
apiVersion: v1
kind: Service
metadata:
  name: polar-rabbitmq
spec:
  selector:
    app: polar-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672