spring:
  application:
    name: token-login
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.tokenlogin.model

jwt:
  issuer: jr0503@naver.com
  secret_key: 55DQ7XtZjKEuftetbQMtw0geU9SS1rR/fbrPOAqIQ2UUPJ+crjXRoLppDtreyvim53v3U6+hTLcbunHlxlNGlA==
